server:
  port: 30180

spring:
  cloud:
    config:
      enabled: false
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
  test:
    database:
      replace: any

database:
  datasource:
    service:
      master:
        url: jdbc:h2:mem:zeroq_service_testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
        driver-class-name: org.h2.Driver
        username: sa
        password:
      slave1:
        url: jdbc:h2:mem:zeroq_service_testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
        driver-class-name: org.h2.Driver
        username: sa
        password:
    admin:
      master:
        url: jdbc:h2:mem:zeroq_admin_testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
        driver-class-name: org.h2.Driver
        username: sa
        password:
      slave1:
        url: jdbc:h2:mem:zeroq_admin_testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
        driver-class-name: org.h2.Driver
        username: sa
        password:
    sensor:
      master:
        url: jdbc:h2:mem:zeroq_sensor_testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
        driver-class-name: org.h2.Driver
        username: sa
        password:
      slave1:
        url: jdbc:h2:mem:zeroq_sensor_testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
        driver-class-name: org.h2.Driver
        username: sa
        password:
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
