server:
  port: 20180

spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false

database:
  datasource:
    service:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/ZEROQ_SERVICE?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/ZEROQ_SERVICE?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    admin:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/ZEROQ_ADMIN?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/ZEROQ_ADMIN?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
    sensor:
      master:
        url: jdbc:mysql://kimd0.iptime.org:23306/ZEROQ_SENSOR?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
      slave1:
        url: jdbc:mysql://kimd0.iptime.org:23306/ZEROQ_SENSOR?zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 8
        connection-timeout: 30000
        maxLifetime: 1800000
